"""
Silver-Tier Reasoning Loop
Processes items from Needs_Action and generates structured Plans.
"""

import os
import re
from pathlib import Path
from datetime import datetime
import logging

# Setup paths
BASE_PATH = Path(__file__).parent.parent
NEEDS_ACTION = BASE_PATH / "Needs_Action"
PLANS_DIR = BASE_PATH / "Plans"
LOGS_DIR = BASE_PATH / "Logs"

PLANS_DIR.mkdir(exist_ok=True)
LOGS_DIR.mkdir(exist_ok=True)

# Logging setup
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(LOGS_DIR / "reasoning_loop_log.md", encoding='utf-8'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

def parse_md_file(filepath):
    """Parse frontmatter and content from a markdown file"""
    try:
        content = filepath.read_text(encoding='utf-8')
        
        # Simple frontmatter parser
        frontmatter = {}
        fm_match = re.search(r'^---(.*?)---', content, re.DOTALL)
        if fm_match:
            fm_text = fm_match.group(1)
            for line in fm_text.strip().split('\n'):
                if ':' in line:
                    key, val = line.split(':', 1)
                    frontmatter[key.strip()] = val.strip()
        
        # Extract body (everything after frontmatter)
        body = content.split('---', 2)[-1].strip()
        return frontmatter, body
    except Exception as e:
        logger.error(f"Error parsing {filepath.name}: {e}")
        return None, None

def generate_plan(filename, frontmatter, body):
    """Generate a structured plan based on item content"""
    item_type = frontmatter.get('type', 'unknown')
    item_from = frontmatter.get('from', 'Unknown')
    item_subject = frontmatter.get('subject', 'No Subject')
    
    plan_id = filename.replace('.md', '')
    plan_filename = f"PLAN_{plan_id}.md"
    plan_path = PLANS_DIR / plan_filename
    
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    # Simple reasoning logic
    priority = "NORMAL"
    next_step = "Review item"
    
    if item_type == 'email':
        if any(word in body.lower() for word in ['urgent', 'asap', 'payment', 'invoice']):
            priority = "HIGH"
            next_step = "Draft urgent reply or process invoice"
        else:
            next_step = "Draft standard email reply"
            
    elif item_type == 'whatsapp':
        priority = "URGENT"
        next_step = "Reply to WhatsApp message immediately"

    plan_content = f"""---
title: Action Plan for {plan_id}
source: {filename}
type: {item_type}
priority: {priority}
status: active
created: {timestamp}
---

# Action Plan: {item_subject if item_type == 'email' else 'WhatsApp from ' + item_from}

## Context
- **From:** {item_from}
- **Type:** {item_type}
- **Snippet:** {body[:200]}...

## Reasoning Logic (Silver Tier)
1. **Item detected** in Needs_Action folder.
2. **Analysis:** {item_type.capitalize()} received from {item_from}.
3. **Sentiment:** {priority.lower()} priority based on keyword analysis.

## Recommended Tasks
- [ ] 🔍 Review original document in Needs_Action/
- [ ] 📝 **Next Step:** {next_step}
- [ ] ✅ Move source file to Done/ after completion
- [ ] 📊 Update Dashboard with action status

---
*Generated by AI Employee Reasoning Loop - Silver Tier*
"""
    
    plan_path.write_text(plan_content, encoding='utf-8')
    return plan_filename

def run_reasoning_loop():
    """Main loop to process all items in Needs_Action"""
    logger.info("🚀 Starting Silver-Tier Reasoning Loop...")
    
    files = list(NEEDS_ACTION.glob("*.md"))
    if not files:
        logger.info("No items found in Needs_Action. Skipping.")
        return

    processed_count = 0
    for file in files:
        if file.name.startswith("PLAN_") or file.name == "README.md" or file.name == "test_file.md":
            continue
            
        logger.info(f"Processing: {file.name}")
        frontmatter, body = parse_md_file(file)
        
        if frontmatter:
            plan_file = generate_plan(file.name, frontmatter, body)
            logger.info(f"✅ Generated plan: {plan_file}")
            processed_count += 1
            
    logger.info(f"✨ Reasoning loop complete. Processed {processed_count} items.")

if __name__ == "__main__":
    run_reasoning_loop()
